//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodTracker_revenge_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public string idRestaurante { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Tipo_comida { get; set; }
        public string Tipo_ambiente { get; set; }
        public string Tipo_restaurante { get; set; }
        public string Ciudad { get; set; }
        public string Telefono { get; set; }
        public Nullable<decimal> Precio_minimo { get; set; }
        public Nullable<decimal> Precio_maximo { get; set; }
        public Nullable<int> Valoracion { get; set; }
    }
}
