//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Tracker__prototype_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_busqueda
    {
        public string IdHistorial { get; set; }
        public string idUsuario { get; set; }
        public string Fecha_busqueda { get; set; }
        public string Ciudad { get; set; }
        public string Tipo_comida { get; set; }
        public string Tipo_restaurante { get; set; }
        public string Tipo_ambiente { get; set; }
        public string Rango_precio { get; set; }
        public string Medio_transporte { get; set; }
    }
}
