//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Tracker__prototype_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string idUsuario { get; set; }
        public string Nombre { get; set; }
        public string Localizacion { get; set; }
        public string Medio_transporte { get; set; }
        public string Nombre_usuario { get; set; }
        public string Contraseña { get; set; }
        public string Correo { get; set; }
    }
}
